name: GitHub Actions Maven Build Example 

on:
  push:
      branches: [master]
jobs:

  build-on-ubuntu:

      runs-on: ubuntu-latest
      steps:
         - name: Step1 - Checkout main branch from GitHub
         uses : actions/checkout@v2

        
   
