name: GitHub Actions Maven Build Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build Maven Project
        run: mvn -e -X --batch-mode -DskipTests package

      - name: Run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

  sonarcloud:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=AB-RAWAJBEH_software-project
